export const SAMPLE_POSTS = [
  {
    id: 6,
    title: '해운대 근처 가족 호텔 추천 부탁드립니다',
    content: '아이와 함께 묵기 좋은 해운대 근처 숙소를 찾고 있습니다.',
    password: '1234',
    createdAt: '2026-07-14',
    topic: '숙박',
    postType: '질문',
    place: '해운대',
    image: '/images/posts/post-6-haeundae-hotel.jpg',
  },
  {
    id: 5,
    title: '광안리 숙소 1박 후기',
    content: '광안리 바다 근처 숙소를 이용했는데 야경을 보기 좋았습니다.',
    password: '1234',
    createdAt: '2026-07-13',
    topic: '숙박',
    postType: '후기',
    place: '광안리',
    image: '/images/posts/post-5-gwangalli-night.jpg',
  },
  {
    id: 4,
    title: '비 오는 날 갈 만한 부산 관광지 있나요?',
    content: '실내에서 이용할 수 있는 부산 관광지를 추천받고 싶습니다.',
    password: '1234',
    createdAt: '2026-07-12',
    topic: '관광',
    postType: '질문',
    image: '/images/posts/post-4-indoor-place.jpg',
  },
  {
    id: 3,
    title: '감천문화마을 방문 후기',
    content: '골목과 전망이 아름다웠지만 경사가 많아서 편한 신발이 필요합니다.',
    password: '1234',
    createdAt: '2026-07-11',
    topic: '관광',
    postType: '후기',
    place: '감천문화마을',
    image: '/images/posts/post-3-gamcheon.jpg',
  },
  {
    id: 2,
    title: '부산 여행 준비하면서 궁금한 점',
    content: '부산 대중교통 이용 팁을 자유롭게 공유해주세요.',
    password: '1234',
    createdAt: '2026-07-10',
    topic: '기타',
    postType: '기타',
    image: '/images/posts/post-2-busan-transport.jpg',
  },
  {
    id: 1,
    title: '부산 여행 자유 이야기',
    content: '부산에서 좋았던 장소를 자유롭게 이야기해 주세요.',
    password: '1234',
    createdAt: '2026-07-09',
    topic: '기타',
    postType: '기타',
    image: '/images/posts/post-1-busan-view.jpg',
  },
];